project:
  type: website
  render: 
  -index.qmd 
  
website:
back-to-top-navigation: True 
page-navigation : True
  title: "Météo"
  navbar:
  title: "Météo à Montpellier sur les 4 prochains jours "
  background: primary
    left:
      - icon: soleil
       href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



