project:
  type: website
  render:
    - index.qmd
website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "HAX712X : Météo à Montpellier"
  site-url: http://arthur-tena.github.io/application_meteo/
  repo-url: http://github.com/arthur-tena/application_meteo
  navbar:
    title: "HAX712X : Développement logiciel"
    background: primary
    search: true
    tools:
      - icon: github
        href: http://github.com/arthur-tena/application_meteo
        text: GitHub
      -icon: sun
       href: https://open-meteo.com/en/docs/meteofrance-api#hourly=temperature_2m,relative_humidity_2m,rain,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,sunrise,sunset&timezone=GMT
       text: open météo
format:
  html:
    toc: true
    theme:
      spacelab
      # light: spacelab
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    number-sections: false
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    # self-contained: true
    # fig-format: svg
    css: custom.scss